### ISSUE TITLE
Any reason to use Debian as base? Why not Alpine?

### ISSUE THREAD

**Issue by DimmKirr** [hivemq/hivemq-docker-images#2]
Thank you for starting this, I'm curious if there are any reasons not to use Alpine Linux these days?

**Comment by fraschbi** [comment]
Hello Dmitry,

Please excuse the delayed response.
There are a multiple reasons, why we are going with the Debian image.
Most importantly: There is no alpine image for the official OpenJDK/JRA 11, leaving this slim image the most compact solution.

Thank you for interest and kind regards,
Florian
