### ISSUE TITLE
Docker image of Community Edition (CE)

### ISSUE THREAD

**Issue by ghost** [hivemq/hivemq-docker-images#5]
Are there any plans to make a Docker image of the Community Edition (CE) available? The current image contains the Enterprise Edition.

Such an image would be useful to run HoveMQ as a [Testcontainer](https://www.testcontainers.org/).

**Comment by MagiErber** [comment]
Hi @lutzhorn,
nice to see your interest. I will close this issue, as it belongs to the [HiveMQ4 Docker Repository](https://github.com/hivemq/hivemq4-docker-images) and has a duplicate [Issue](https://github.com/hivemq/hivemq4-docker-images/issues/9) there.
Best regards,
Magi
