### ISSUE TITLE
Docker image information update.

### ISSUE THREAD

**Issue by frankyfish** [hivemq/hivemq-docker-images#7]
Hello, could you please update or make readme for docker image more clear?
Namely the part with `HIVEMQ_WEB_UI_PASSWORD ` it states that `_SHA256 of adminhivemq (default)_` is used as default password while it is actually  `hivemq` as stated here: https://www.hivemq.com/downloads/docker/
Took me some time to find out this information as I mostly accustomed with reading image details information on docker hub. Though doc is mentioning hivemq4 default credentials are the same for hivemq/hivemq3.
Thanks in advance!

**Comment by fraschbi** [comment]
Hi @frankyfish,
Thank you for the feedback. 
The information is correct. As can be seen in the [HiveMQ User Guide](https://www.hivemq.com/docs/hivemq/3.4/web-ui/configuration.html#user-configuration)

> The password of the user as a SHA256 hash without iterations and **with the user name as prepended salt**.

Kind regards,
Florian
