### ISSUE TITLE
HiveMQ Docker Image with tag dns-3.4.6 contains HiveMQ v3.4.5

### ISSUE THREAD

**Issue by DT-TeamNova** [hivemq/hivemq-docker-images#8]
Pulling _hivemq/hivemq3:dns-3.4.6_ from official HiveMQ registry on docker hub results in getting an image which actually contains v.3.4.5.
Looks like some mistake during image build, could you please take a look.

docker run -it hivemq/hivemq3:dns-3.4.6 bash
Unable to find image 'hivemq/hivemq3:dns-3.4.6' locally
dns-3.4.6: Pulling from hivemq/hivemq3
8d691f585fa8: Pull complete 
3da6fe7ff2ef: Pull complete 
02c32ad92c0d: Pull complete 
c5b17f485691: Pull complete 
ff5e3b928815: Pull complete 
f7b1688a9972: Pull complete 
986a2120b368: Pull complete 
d1c7611b0565: Pull complete 
06fd0bc7fb51: Pull complete 
c35dd8ff24b3: Pull complete 
975bc4e67025: Pull complete 
c8fe31b39fb7: Pull complete 
Digest: sha256:00584b5e4afb989bdc16c39d57945cf6254e0019293f53ccf59f7b05bd5d2bce
Status: Downloaded newer image for hivemq/hivemq3:dns-3.4.6
Getting bind address from container hostname
hivemq@444144de99c3:/opt/hivemq-3.4.5$
hivemq@444144de99c3:/opt/hivemq-3.4.5$ cd ..
hivemq@444144de99c3:/opt$ ls 
docker-entrypoint.sh  hivemq  hivemq-3.4.5

Or may be default directory name is incorrect.

**Comment by fraschbi** [comment]
Hi @DT-TeamNova ,
Thank you for making us aware of this.
It is now fixed and you can pull the HiveMQ 3.4.6 images with the `3.4.6` or `latest` tag.
Best,
Florian
